#pragma once

#define CONFIG_HOSTNAME "ESP32_RELAY"

#define CONFIG_WIFI_SSID "Nemiland"
#define CONFIG_WIFI_PASSWORD "Patryk13"

#define CONFIG_MQTT_BROKER "mqtt://192.168.1.30:1883"
#define CONFIG_MQTT_TOPIC_BASE    "esp32"
#define CONFIG_MQTT_TOPIC_RELAY_A "relay0"
#define CONFIG_MQTT_TOPIC_RELAY_B "relay1"

#define CONFIG_GPIO_LED     15
#define CONFIG_GPIO_RELAY_A 5
#define CONFIG_GPIO_RELAY_B 3

// #define CONFIG_RELAY_NORMAL_OPEN
#define CONFIG_RELAY_NORMAL_CLOSED

#define CONFIG_RELAY_AFTER_RESET_ENABLE
// #define CONFIG_RELAY_AFTER_RESET_DISABLE

